### PR TITLE
gocli: fix ssh command tty size

### LINKED ISSUE #1280: When SSHing into a KubevirtCI, long terminal commands are not wrapped, therefore looking weird
**What happened**:
When SSHing into a KubevirtCI node, if the command is long enough, it is not warpped by instead being messy overriding the beginning of the command:

```shell
> ./cluster-up/ssh.sh node02
Last login: Sun Sep 15 08:35:14 2024 from 192.168.66.2

# This is short enough, looking good
[vagrant@node02 ~]$ find -regex '.*pod.*' -type d -exec cat {}/memory.max \;
[vagrant@node02 ~]$

# Adding `&& ls {}` at the end of the find exec command
{} \;t@node02 ~]$                                                            s \;                                                                          l 
\;agrant@node02 ~]$ find -regex '.*pod.*' -type d -exec cat {}/memory.max &&  \;
```

This is how it looks like:
image

**What you expected to happen**:
The command to be wrapped into a new line in a human-readable way.

**How to reproduce it (as minimally and precisely as possible)**:
As explained above. 100% reproducible.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.3 (main)

### PR DESCRIPTION
**Pull request by Acedus**
**What this PR does / why we need it**:
SSH sessions into cluster nodes don't inherit the terminal size from the exec session, resulting in a tty size 0 0.
PR adds handling of `SIGWINCH` signals to propagate terminal resize events, preventing the remote tty from defaulting to size 0 0.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1280

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Acedus** [comment]
/cc @iholder101 @akalenyu 

Had enough of warped terminals...

**Comment by Acedus** [comment]
fyi @Sapthagiri777

File: cluster-provision/gocli/docker/docker.go [hunk 1]
```diff
@@ -139,7 +140,7 @@ func Terminal(cli *client.Client, container string, args []string, file *os.File
 	ctx := context.Background()
 	id, err := cli.ContainerExecCreate(ctx, container, types.ExecConfig{
 		Privileged:   true,
-		Tty:          terminal.IsTerminal(int(file.Fd())),
+		Tty:          true,
```
Comment (oshoval) [inline cluster-provision/gocli/docker/docker.go:143]: i remember vaguly sometimes we shouldnt use tty ?
it might break those if correct

**Review by oshoval — COMMENTED** [review]
Nice, thought the same lately

what about doing `stty cols 500 rows 500` in the provision instead please ?
it will be safer in case the inline comments are right

File: cluster-provision/gocli/docker/docker.go (hunk 1 above)
Comment (Acedus) [reply cluster-provision/gocli/docker/docker.go:143]: We error out early if that isn't the case anyway.

File: cluster-provision/gocli/docker/docker.go
Comment (oshoval) [inline cluster-provision/gocli/docker/docker.go:1]: this will affect also podman ? was it tested ?

File: cluster-provision/gocli/docker/docker.go [hunk 2]
```diff
@@ -164,6 +165,17 @@ func Terminal(cli *client.Client, container string, args []string, file *os.File
 	if err != nil {
 		return -1, err
 	}
+	defer terminal.Restore(int(file.Fd()), state)
```
Comment (oshoval) [inline cluster-provision/gocli/docker/docker.go:168]: https://github.com/kubevirt/kubevirtci/pull/1511/files#diff-1acc43c959633b89c10efaff8a0c2afc8582dc4b290b34948bc6c65a4c343c1eR199

you have it here already

File: cluster-provision/gocli/docker/docker.go (hunk 1 above)
Comment (oshoval) [reply cluster-provision/gocli/docker/docker.go:143]: can you show me in the code where please ?

**Review by oshoval — COMMENTED** [review]
was it tested for remote connections please ?

File: cluster-provision/gocli/docker/docker.go (hunk 2 above)
Comment (Acedus) [reply cluster-provision/gocli/docker/docker.go:168]: Oversight, thanks.

File: cluster-provision/gocli/docker/docker.go [hunk 3]
```diff
@@ -165,6 +166,16 @@ func Terminal(cli *client.Client, container string, args []string, file *os.File
 		return -1, err
 	}
 
+	resizeCh := make(chan os.Signal, 1)
+	signal.Notify(resizeCh, syscall.SIGWINCH)
+	resizeTerminal(context.Background(), cli, id.ID, file)
```
Comment (enp0s3) [inline cluster-provision/gocli/docker/docker.go:171]: @Acedus Small nit - perhaps we should reuse the context variable

**Comment by Acedus** [comment]
[Change](https://github.com/kubevirt/kubevirtci/compare/50f1665ad40518cb418bd6cc7a4eaef76413b825..f0b525c5d96197b9bd69297a363e394c7dc41813) - Adressed @enp0s3' comments.

**Review by enp0s3 — COMMENTED** [review]
@Acedus Thank you!
/approve

**Comment by Acedus** [comment]
> Wdyt about just setting `stty cols 500 rows 500` ? instead dynamic adjusting
> 
> This is what we are doing on kubevirt Expecters, and it works great

On certain window sizes and compositors it doesn't work all that way, is there an issue with dynamic resizing?
