### PR TITLE
conformance: Fix filter for conformance tests after change to default behaviour

### LINKED ISSUE #1434: KubeVirt conformance tests failing on all kubevirtci provider presubmit lanes due to missing kubectl binary
The kubevirtci presubmit lanes have been failing consistently since around 2025-04-18. 

From looking into the sonobuoy logs I can see the tests are failing due to no VolumeSnapshot support

```
  Timeline >>
  [FAILED] in [BeforeEach] - tests/storage/datavolume.go:708 @ 05/02/25 08:44:45.685
  On failure, artifacts will be collected in /tmp/sonobuoy/results/k8s-reporter/6_*
  STEP: Collecting Logs due to failure @ 05/02/25 08:44:45.685
  {"command":"kubectl get all --all-namespaces -o wide","component":"tests","level":"error","msg":"command failed","pos":"command.go:115","reason":"no kubectl binary specified","timestamp":"2025-05-02T08:44:45.731184Z"}
  Skipping volume snapshot log collection
  Global test cleanup started.
  Global test cleanup ended.
  << Timeline

  [FAILED] Failing test, no VolumeSnapshot support
  In [BeforeEach] at: tests/storage/datavolume.go:708 @ 05/02/25 08:44:45.685
------------------------------
W0502 08:44:53.850990       7 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
failed to fetch cluster overview: command failed: no kubectl binary specified,
W0502 08:44:55.177644       7 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
• [FAILED] [8.201 seconds]
[sig-storage] DataVolume Integration [rfe_id:3188][crit:high][vendor:cnv-qe@redhat.com][level:system] DataVolume clone permission checking using Alpine import/clone [BeforeEach] [storage-req] deny then allow clone request with implicit sufficient role snapshot clone [sig-storage, RequiresSnapshotStorageClass, conformance, storage-req]
  [BeforeEach] tests/storage/datavolume.go:704
  [It] tests/storage/datavolume.go:969

  Timeline >>
  [FAILED] in [BeforeEach] - tests/storage/datavolume.go:708 @ 05/02/25 08:44:53.85
  On failure, artifacts will be collected in /tmp/sonobuoy/results/k8s-reporter/7_*
  STEP: Collecting Logs due to failure @ 05/02/25 08:44:53.85
  {"command":"kubectl get all --all-namespaces -o wide","component":"tests","level":"error","msg":"command failed","pos":"command.go:115","reason":"no kubectl binary specified","timestamp":"2025-05-02T08:44:53.977331Z"}
  Skipping volume snapshot log collection
  Global test cleanup started.
  Global test cleanup ended.
  << Timeline

  [FAILED] Failing test, no VolumeSnapshot support
  In [BeforeEach] at: tests/storage/datavolume.go:708 @ 05/02/25 08:44:53.85
------------------------------
W0502 08:45:02.056177       7 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
failed to fetch cluster overview: command failed: no kubectl binary specified,
W0502 08:45:03.515953       7 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
• [FAILED] [8.330 seconds]
[sig-storage] DataVolume Integration [rfe_id:3188][crit:high][vendor:cnv-qe@redhat.com][level:system] DataVolume clone permission checking using Alpine import/clone [BeforeEach] [storage-req] deny then allow clone request with explicit role (all namespaces) snapshot clone [sig-storage, RequiresSnapshotStorageClass, conformance, storage-req]
  [BeforeEach] tests/storage/datavolume.go:704
  [It] tests/storage/datavolume.go:970
```
source: https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1430/check-provision-k8s-1.31/1918218498065043456/artifacts/

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

The default behaviour of the conformance image was recently changed[1] which has led to more tests being included that cause the check-provision test lanes to fail.

Update the filter to remove the tests that are not supposed to run in the kubevirtci check-provision test lanes.

[1] https://github.com/kubevirt/kubevirt/pull/14509

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1434

**Special notes for your reviewer**:
/cc @dhiller 

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

Thank you :100: @brianmcarey !

**Comment by dhiller** [comment]
@brianmcarey something's odd: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1440/check-provision-k8s-1.32/1919733586555047936#1:build-log.txt%3A2663

File: cluster-provision/k8s/check-cluster-up.sh [hunk 1]
```diff
@@ -98,7 +98,10 @@ export KUBEVIRTCI_GOCLI_CONTAINER=quay.io/kubevirtci/gocli:latest
                 ${ksh} patch -n kubevirt kv kubevirt --type='merge' --patch '{"spec": {"configuration": {"seccompConfiguration": {"virtualMachineInstanceProfile": {"customProfile": {"localhostProfile" : "kubevirt/kubevirt.json"} } } } } }'
             fi
 
-            export SONOBUOY_EXTRA_ARGS="--plugin https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/conformance${arch_suffix}.yaml"
+            export LABEL_FILTER="((conformance) && !(RequiredSnapshotStorageClass,RequiredBlockStorage))"
+
+            export SONOBUOY_EXTRA_ARGS="--plugin https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/conformance${arch_suffix}.yaml --plugin-env kubevirt-conformance.E2E_LABEL=${LABEL_FILTER}"
```
Comment (akalenyu) [inline cluster-provision/k8s/check-cluster-up.sh:103]: argument splitting is a pain. try dropping spaces?
`(conformance)&&(!RequiresSnapshotStorageClass)&&(!RequiresBlockStorage)`
(also note that logically the current version is not equivalent to the one I was advocating for)

Comment (brianmcarey) [reply cluster-provision/k8s/check-cluster-up.sh:103]: that looks better - thanks @akalenyu .

**Review by dhiller — APPROVED** [review]
Thank you @brianmcarey ! :tada:

**Comment by brianmcarey** [comment]
```
[38;5;9m[1mSummarizing 5 Failures:[0m
  [38;5;9m[FAIL][0m [0m[sig-storage] Storage [38;5;243mStarting a VirtualMachineInstance [0m[rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC [38;5;243mshould be successfully [0mstarted [38;5;9m[1m[It] [test_id:3130]with Disk PVC[0m [38;5;204m[sig-storage, conformance][0m
  [38;5;243mtests/watcher/watcher.go:195[0m
  [38;5;9m[FAIL][0m [0m[sig-storage] Storage [38;5;243mStarting a VirtualMachineInstance [0m[rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC [38;5;243mshould be successfully [0mstarted [38;5;9m[1m[It] [test_id:3131]with CDRom PVC[0m [38;5;204m[sig-storage, conformance][0m
  [38;5;243mtests/watcher/watcher.go:195[0m
  [38;5;9m[FAIL][0m [0m[sig-storage] Storage [38;5;243mStarting a VirtualMachineInstance [0m[rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC [38;5;243mshould be successfully [0mstarted [38;5;9m[1m[It] hostpath disk image file not owned by qemu[0m [38;5;204m[sig-storage, conformance][0m
  [38;5;243mtests/watcher/watcher.go:195[0m
  [38;5;9m[FAIL][0m [0m[sig-storage] Storage [38;5;243mStarting a VirtualMachineInstance [0m[rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]With ephemeral alpine PVC [38;5;243mshould be successfully [38;5;9m[1m[It] [test_id:3136]started with Ephemeral PVC[0m [38;5;204m[sig-storage, conformance][0m
  [38;5;243mtests/watcher/watcher.go:195[0m
  [38;5;214m[TIMEDOUT][0m [0m[sig-compute] [rfe_id:1177][crit:medium] VirtualMachine [38;5;243mwith paused vmi [38;5;214m[1m[It] [test_id:3085]should be stopped successfully[0m [38;5;204m[sig-compute, conformance][0m
  [38;5;243mtests/compute/vm_lifecycle.go:138[0m

[38;5;9m[1mRan 71 of 1385 Specs in 3628.667 seconds[0m
[38;5;9m[1mFAIL! - Suite Timeout Elapsed[0m -- [38;5;10m[1m66 Passed[0m | [38;5;9m[1m5 Failed[0m | [38;5;11m[1m3 Pending[0m | [38;5;14m[1m1311 Skipped[0m
--- FAIL: TestTests (3630.78s)
```

The PVC tests all failed with permission issues:
```
[38;5;9m[FAILED] Unexpected Warning event received: testvmi-j58zp,4fd9f034-8652-4c09-857f-98fda94ee70f: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2025-05-07T08:48:11.689409Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-private/vmi-disks/disk0/disk.img\",\"node-name\":\"libvirt-1-storage\",\"read-only\":true,\"cache\":{\"direct\":false,\"no-flush\":false}}: Could not open '/var/run/kubevirt-private/vmi-disks/disk0/disk.img': Permission denied')"
  Expected
      <string>: Warning
  not to equal
      <string>: Warning[0m
```
source: https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1440/check-provision-k8s-1.32/1920019222256160768/artifacts/

**Comment by brianmcarey** [comment]
These are tests that we ran before: 
image

source: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1320/check-provision-k8s-1.30/1854591419491028992

I think I am ok to filter out the sig-storage tests as these were not previously run.

**Comment by akalenyu** [comment]
> These are tests that we ran before: image
> 
> source: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1320/check-provision-k8s-1.30/1854591419491028992
> 
> I think I am ok to filter out the sig-storage tests as these were not previously run.

That sounds good, I'm afraid these tests are coupled to one of the kubevirt test containers (disks-images-provider) and thus won't work without it. That dependency disqualifies them from being conformance tests, unfortunately.

Note that is not the only problem. The suite timed out - you will probably still reach the 1hour ginkgo default timeout without them. I think we should allow extending the timeout in the conformance app

**Review by dhiller — APPROVED** [review]
Thanks @brianmcarey !
