### PR TITLE
fix: Run etcd mount commands with sudo

### LINKED ISSUE #1222: ssh issue wrt sudo when using etcd in-memory
**What happened**:
[kubevirtci rewrite](https://github.com/kubevirt/kubevirtci/pull/1209) introduced an ssh issue wrt sudo when using etcd in-memory [1]. `sudo` on mount for in memory was dropped [2]

**What you expected to happen**:
Running kubevirtci with in-memory etcd should not fail on mounting.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
/sig ci

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12310/pull-kubevirt-e2e-k8s-1.30-sig-operator/1813477609900609536#1:build-log.txt%3A333
[2]: https://github.com/kubevirt/kubevirtci/pull/1209/files#diff-12e7b6e3d4ce92e7d50b6cd0e3aebac95e9480cb4dbbe4a220e1c86c3b12f6ebL895

### PR DESCRIPTION
**Pull request by aerosouund**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1222

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### CODE REVIEW

**Comment by aerosouund** [comment]
@xpivarc @brianmcarey

**Comment by brianmcarey** [comment]
I think the test needs to be updated too - https://github.com/kubevirt/kubevirtci/blob/a087e7e153c809f9c1087cb8d8378b2bc1c6489c/cluster-provision/gocli/cmd/run_test.go#L35

**Comment by aerosouund** [comment]
> I think the test needs to be updated too -
> 
> https://github.com/kubevirt/kubevirtci/blob/a087e7e153c809f9c1087cb8d8378b2bc1c6489c/cluster-provision/gocli/cmd/run_test.go#L35

Added to the test

File: cluster-provision/gocli/cmd/run_test.go [hunk 1]
```diff
@@ -30,10 +30,10 @@ var _ = Describe("Node Provisioning", func() {
 		It("should execute the correct commands", func() {
 			n := nodesconfig.NewNodeLinuxConfig(1, "k8s-1.30", "", "512M", "", false, true, true, true, true, true)
```
Comment (brianmcarey) [inline cluster-provision/gocli/cmd/run_test.go:31]: It may be worth looking at making the provider name more dynamic rather then statically setting `k8s-1.30` - the k8s-1.30 provider will be removed at some point in the future. 

This could be handled in a follow up PR - doesn't have to be included in this fix.
